/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.CaptchaResponse = factory(root.Cyclos471Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CaptchaResponse model module.
   * @module model/CaptchaResponse
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>CaptchaResponse</code>.
   * Data sent to the server containing the response of an user to a captcha challenge 
   * @alias module:model/CaptchaResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CaptchaResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaptchaResponse} obj Optional instance to populate.
   * @return {module:model/CaptchaResponse} The populated <code>CaptchaResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('challenge')) {
        obj['challenge'] = ApiClient.convertToType(data['challenge'], 'String');
      }
      if (data.hasOwnProperty('response')) {
        obj['response'] = ApiClient.convertToType(data['response'], 'String');
      }
    }
    return obj;
  }

  /**
   * The captcha challenge identifier
   * @member {String} challenge
   */
  exports.prototype['challenge'] = undefined;
  /**
   * The captcha response, as informed by the user
   * @member {String} response
   */
  exports.prototype['response'] = undefined;



  return exports;
}));


