/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.ChangeForgottenPassword = factory(root.Cyclos471Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ChangeForgottenPassword model module.
   * @module model/ChangeForgottenPassword
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>ChangeForgottenPassword</code>.
   * The parameters for confirming a forgotten password reset
   * @alias module:model/ChangeForgottenPassword
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ChangeForgottenPassword</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChangeForgottenPassword} obj Optional instance to populate.
   * @return {module:model/ChangeForgottenPassword} The populated <code>ChangeForgottenPassword</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('key')) {
        obj['key'] = ApiClient.convertToType(data['key'], 'String');
      }
      if (data.hasOwnProperty('newPassword')) {
        obj['newPassword'] = ApiClient.convertToType(data['newPassword'], 'String');
      }
      if (data.hasOwnProperty('securityAnswer')) {
        obj['securityAnswer'] = ApiClient.convertToType(data['securityAnswer'], 'String');
      }
    }
    return obj;
  }

  /**
   * The key received by e-mail on the forgotten password reset request 
   * @member {String} key
   */
  exports.prototype['key'] = undefined;
  /**
   * The new password value. Required when the password is manual. 
   * @member {String} newPassword
   */
  exports.prototype['newPassword'] = undefined;
  /**
   * When a security question is asked, this is the answer, and is required. 
   * @member {String} securityAnswer
   */
  exports.prototype['securityAnswer'] = undefined;



  return exports;
}));


