/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ConflictErrorCode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ConflictErrorCode'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.ConflictError = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.ConflictErrorCode);
  }
}(this, function(ApiClient, ConflictErrorCode) {
  'use strict';




  /**
   * The ConflictError model module.
   * @module model/ConflictError
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>ConflictError</code>.
   * Error returned when there was a conflict with some expected status vs the actual database status
   * @alias module:model/ConflictError
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ConflictError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConflictError} obj Optional instance to populate.
   * @return {module:model/ConflictError} The populated <code>ConflictError</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('code')) {
        obj['code'] = ConflictErrorCode.constructFromObject(data['code']);
      }
    }
    return obj;
  }

  /**
   * Error codes for 409 Conflict entity HTTP status  Possible values are: * staleEntity: Failure in the optimistic lock. It means some entity was fetched for editing by 2 clients. Then they both saved it. The first one is successful, but the second one will fail. If you get this error, make sure the `version` field is being sent with the correct value, as fetched from the server. * constraintViolatedOnRemove: An attempt to remove some entity has failed, probably because that entity is in use, that is, is being referenced by some other entity.  
   * @member {module:model/ConflictErrorCode} code
   */
  exports.prototype['code'] = undefined;



  return exports;
}));


