/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.CustomFieldDynamicValue = factory(root.Cyclos471Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CustomFieldDynamicValue model module.
   * @module model/CustomFieldDynamicValue
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>CustomFieldDynamicValue</code>.
   * Represents a single possible value of a dynamic custom field 
   * @alias module:model/CustomFieldDynamicValue
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>CustomFieldDynamicValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomFieldDynamicValue} obj Optional instance to populate.
   * @return {module:model/CustomFieldDynamicValue} The populated <code>CustomFieldDynamicValue</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('defaultValue')) {
        obj['defaultValue'] = ApiClient.convertToType(data['defaultValue'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * The internal value
   * @member {String} value
   */
  exports.prototype['value'] = undefined;
  /**
   * The display label
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * The value that should be suggested as default.
   * @member {Boolean} defaultValue
   */
  exports.prototype['defaultValue'] = undefined;



  return exports;
}));


