/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BigDecimal', 'model/CustomField', 'model/CustomFieldDynamicValue', 'model/CustomFieldPossibleValue', 'model/Entity', 'model/EntityReference'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BigDecimal'), require('./CustomField'), require('./CustomFieldDynamicValue'), require('./CustomFieldPossibleValue'), require('./Entity'), require('./EntityReference'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.CustomFieldValue = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.BigDecimal, root.Cyclos471Api.CustomField, root.Cyclos471Api.CustomFieldDynamicValue, root.Cyclos471Api.CustomFieldPossibleValue, root.Cyclos471Api.Entity, root.Cyclos471Api.EntityReference);
  }
}(this, function(ApiClient, BigDecimal, CustomField, CustomFieldDynamicValue, CustomFieldPossibleValue, Entity, EntityReference) {
  'use strict';




  /**
   * The CustomFieldValue model module.
   * @module model/CustomFieldValue
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>CustomFieldValue</code>.
   * Holds detailed information about a custom field value. The actual value should be read from a property depending on the field type. If the type is either &#x60;string&#x60;, &#x60;text&#x60;, &#x60;richText&#x60; or &#x60;url&#x60;, the property containing the value is &#x60;stringValue&#x60;. If the type is &#x60;integer&#x60;, the property is &#x60;integerValue&#x60;. If &#x60;decimal&#x60;, &#x60;decimalValue&#x60;. If &#x60;date&#x60;, &#x60;dateValue&#x60;. If &#x60;bool&#x60;, &#x60;booleanValue&#x60;. If either &#x60;singleSelection&#x60; or &#x60;multiSelection&#x60;, &#x60;possibleValues&#x60;. If &#x60;dynamicSelection&#x60;, &#x60;dynamicValue&#x60;. Finally, if &#x60;linkedEntity&#x60;, &#x60;linkedEntityValue&#x60;.   
   * @alias module:model/CustomFieldValue
   * @class
   * @implements module:model/Entity
   */
  var exports = function() {
    var _this = this;

    Entity.call(_this);









  };

  /**
   * Constructs a <code>CustomFieldValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomFieldValue} obj Optional instance to populate.
   * @return {module:model/CustomFieldValue} The populated <code>CustomFieldValue</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('field')) {
        obj['field'] = CustomField.constructFromObject(data['field']);
      }
      if (data.hasOwnProperty('stringValue')) {
        obj['stringValue'] = ApiClient.convertToType(data['stringValue'], 'String');
      }
      if (data.hasOwnProperty('dateValue')) {
        obj['dateValue'] = ApiClient.convertToType(data['dateValue'], 'Date');
      }
      if (data.hasOwnProperty('booleanValue')) {
        obj['booleanValue'] = ApiClient.convertToType(data['booleanValue'], 'Boolean');
      }
      if (data.hasOwnProperty('integerValue')) {
        obj['integerValue'] = ApiClient.convertToType(data['integerValue'], 'Number');
      }
      if (data.hasOwnProperty('decimalValue')) {
        obj['decimalValue'] = ApiClient.convertToType(data['decimalValue'], BigDecimal);
      }
      if (data.hasOwnProperty('enumeratedValues')) {
        obj['enumeratedValues'] = ApiClient.convertToType(data['enumeratedValues'], [CustomFieldPossibleValue]);
      }
      if (data.hasOwnProperty('linkedEntityValue')) {
        obj['linkedEntityValue'] = EntityReference.constructFromObject(data['linkedEntityValue']);
      }
      if (data.hasOwnProperty('dynamicValue')) {
        obj['dynamicValue'] = CustomFieldDynamicValue.constructFromObject(data['dynamicValue']);
      }
    }
    return obj;
  }

  /**
   * The custom field reference
   * @member {module:model/CustomField} field
   */
  exports.prototype['field'] = undefined;
  /**
   * The field value if the field type is either `string`, `text`, `richText` or `url`. 
   * @member {String} stringValue
   */
  exports.prototype['stringValue'] = undefined;
  /**
   * The field value if the field type is `date`. 
   * @member {Date} dateValue
   */
  exports.prototype['dateValue'] = undefined;
  /**
   * The field value if the field type is `bool`. 
   * @member {Boolean} booleanValue
   */
  exports.prototype['booleanValue'] = undefined;
  /**
   * The field value if the field type is `integer`. 
   * @member {Number} integerValue
   */
  exports.prototype['integerValue'] = undefined;
  /**
   * The field value if the field type is `decimal`. 
   * @member {module:model/BigDecimal} decimalValue
   */
  exports.prototype['decimalValue'] = undefined;
  /**
   * The field value if the field type is either `singleSelection` or `multiSelection`. For single selections will either be an empty array or an array with a single elemenet 
   * @member {Array.<module:model/CustomFieldPossibleValue>} enumeratedValues
   */
  exports.prototype['enumeratedValues'] = undefined;
  /**
   * The field value if the field type is `linkedEntity`. 
   * @member {module:model/EntityReference} linkedEntityValue
   */
  exports.prototype['linkedEntityValue'] = undefined;
  /**
   * The field value if the field type is `dynamicSelection`. 
   * @member {module:model/CustomFieldDynamicValue} dynamicValue
   */
  exports.prototype['dynamicValue'] = undefined;

  // Implement Entity interface:
  /**
   * Entity identifier
   * @member {String} id
   */
exports.prototype['id'] = undefined;



  return exports;
}));


