/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CaptchaResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CaptchaResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.ForgottenPasswordRequest = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.CaptchaResponse);
  }
}(this, function(ApiClient, CaptchaResponse) {
  'use strict';




  /**
   * The ForgottenPasswordRequest model module.
   * @module model/ForgottenPasswordRequest
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>ForgottenPasswordRequest</code>.
   * Definitions to request a forgotten password reset
   * @alias module:model/ForgottenPasswordRequest
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ForgottenPasswordRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ForgottenPasswordRequest} obj Optional instance to populate.
   * @return {module:model/ForgottenPasswordRequest} The populated <code>ForgottenPasswordRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('user')) {
        obj['user'] = ApiClient.convertToType(data['user'], 'String');
      }
      if (data.hasOwnProperty('captcha')) {
        obj['captcha'] = CaptchaResponse.constructFromObject(data['captcha']);
      }
    }
    return obj;
  }

  /**
   * An identification method for the user. Allows the same identification methods (principal types) as the login, plus e-mail. 
   * @member {String} user
   */
  exports.prototype['user'] = undefined;
  /**
   * The captcha response required when something is returned in `DataForLogin.forgotPasswordCaptchaProvider`.
   * @member {module:model/CaptchaResponse} captcha
   */
  exports.prototype['captcha'] = undefined;



  return exports;
}));


