/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountWithOwner', 'model/BigDecimal', 'model/CustomFieldValue', 'model/PasswordInput', 'model/TransactionPreview'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountWithOwner'), require('./BigDecimal'), require('./CustomFieldValue'), require('./PasswordInput'), require('./TransactionPreview'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.InternalTransactionPreview = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.AccountWithOwner, root.Cyclos471Api.BigDecimal, root.Cyclos471Api.CustomFieldValue, root.Cyclos471Api.PasswordInput, root.Cyclos471Api.TransactionPreview);
  }
}(this, function(ApiClient, AccountWithOwner, BigDecimal, CustomFieldValue, PasswordInput, TransactionPreview) {
  'use strict';




  /**
   * The InternalTransactionPreview model module.
   * @module model/InternalTransactionPreview
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>InternalTransactionPreview</code>.
   * Base definitions for a preview before performing an internal transaction 
   * @alias module:model/InternalTransactionPreview
   * @class
   * @implements module:model/TransactionPreview
   */
  var exports = function() {
    var _this = this;

    TransactionPreview.call(_this);


  };

  /**
   * Constructs a <code>InternalTransactionPreview</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InternalTransactionPreview} obj Optional instance to populate.
   * @return {module:model/InternalTransactionPreview} The populated <code>InternalTransactionPreview</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      TransactionPreview.constructFromObject(data, obj);
      if (data.hasOwnProperty('pendingAuthorization')) {
        obj['pendingAuthorization'] = ApiClient.convertToType(data['pendingAuthorization'], 'Boolean');
      }
      if (data.hasOwnProperty('toAccount')) {
        obj['toAccount'] = AccountWithOwner.constructFromObject(data['toAccount']);
      }
    }
    return obj;
  }

  /**
   * Indicates whether the transaction would be initially pending authorization in order to be processed 
   * @member {Boolean} pendingAuthorization
   */
  exports.prototype['pendingAuthorization'] = undefined;
  /**
   * A reference to the destination account
   * @member {module:model/AccountWithOwner} toAccount
   */
  exports.prototype['toAccount'] = undefined;

  // Implement TransactionPreview interface:
  /**
   * If configured in the payment type, is a message to be shown to the user before confirming the transaction 
   * @member {String} confirmationMessage
   */
exports.prototype['confirmationMessage'] = undefined;

  /**
   * If a confirmation password is used, contains the definitions on how to request that password from the user. This confirmation password is required when performing sensible actions. Sometimes this is dynamic, for example, the confirmation might be configured to be used only once per session, or operations like payments may have a limit per day to be without confirmation (pinless). 
   * @member {module:model/PasswordInput} confirmationPasswordInput
   */
exports.prototype['confirmationPasswordInput'] = undefined;

  /**
   * A reference to the origin account
   * @member {module:model/AccountWithOwner} fromAccount
   */
exports.prototype['fromAccount'] = undefined;

  /**
   * The final total transaction amount
   * @member {module:model/BigDecimal} totalAmount
   */
exports.prototype['totalAmount'] = undefined;

  /**
   * The list of custom field values, in a detailed view
   * @member {Array.<module:model/CustomFieldValue>} customValues
   */
exports.prototype['customValues'] = undefined;



  return exports;
}));


