/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.MarketplacePermissions = factory(root.Cyclos471Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MarketplacePermissions model module.
   * @module model/MarketplacePermissions
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>MarketplacePermissions</code>.
   * Permissions for the marketplace
   * @alias module:model/MarketplacePermissions
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>MarketplacePermissions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MarketplacePermissions} obj Optional instance to populate.
   * @return {module:model/MarketplacePermissions} The populated <code>MarketplacePermissions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('search')) {
        obj['search'] = ApiClient.convertToType(data['search'], 'Boolean');
      }
      if (data.hasOwnProperty('ownAdvertisements')) {
        obj['ownAdvertisements'] = ApiClient.convertToType(data['ownAdvertisements'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Permission to search the marketplace
   * @member {Boolean} search
   */
  exports.prototype['search'] = undefined;
  /**
   * Permission to manage own simple advertisements
   * @member {Boolean} ownAdvertisements
   */
  exports.prototype['ownAdvertisements'] = undefined;



  return exports;
}));


