/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.NfcTokenParameter = factory(root.Cyclos471Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The NfcTokenParameter model module.
   * @module model/NfcTokenParameter
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>NfcTokenParameter</code>.
   * Definitions for parameters of actions over NFC tokens 
   * @alias module:model/NfcTokenParameter
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>NfcTokenParameter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NfcTokenParameter} obj Optional instance to populate.
   * @return {module:model/NfcTokenParameter} The populated <code>NfcTokenParameter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('token')) {
        obj['token'] = ApiClient.convertToType(data['token'], 'String');
      }
    }
    return obj;
  }

  /**
   * Either the identifier or internal name of fhe NFC token type
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * The token value. Is normally the internal tag idenfifier, encoded as hex   
   * @member {String} token
   */
  exports.prototype['token'] = undefined;



  return exports;
}));


