/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AvailabilityEnum', 'model/PhoneConfiguration', 'model/PhoneNew'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AvailabilityEnum'), require('./PhoneConfiguration'), require('./PhoneNew'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.PhoneConfigurationForUserRegistration = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.AvailabilityEnum, root.Cyclos471Api.PhoneConfiguration, root.Cyclos471Api.PhoneNew);
  }
}(this, function(ApiClient, AvailabilityEnum, PhoneConfiguration, PhoneNew) {
  'use strict';




  /**
   * The PhoneConfigurationForUserRegistration model module.
   * @module model/PhoneConfigurationForUserRegistration
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>PhoneConfigurationForUserRegistration</code>.
   * Contains extended phone configuration used on user registration
   * @alias module:model/PhoneConfigurationForUserRegistration
   * @class
   * @implements module:model/PhoneConfiguration
   */
  var exports = function() {
    var _this = this;

    PhoneConfiguration.call(_this);




  };

  /**
   * Constructs a <code>PhoneConfigurationForUserRegistration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PhoneConfigurationForUserRegistration} obj Optional instance to populate.
   * @return {module:model/PhoneConfigurationForUserRegistration} The populated <code>PhoneConfigurationForUserRegistration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      PhoneConfiguration.constructFromObject(data, obj);
      if (data.hasOwnProperty('mobilePhone')) {
        obj['mobilePhone'] = PhoneNew.constructFromObject(data['mobilePhone']);
      }
      if (data.hasOwnProperty('landLinePhone')) {
        obj['landLinePhone'] = PhoneNew.constructFromObject(data['landLinePhone']);
      }
      if (data.hasOwnProperty('mobileAvailability')) {
        obj['mobileAvailability'] = AvailabilityEnum.constructFromObject(data['mobileAvailability']);
      }
      if (data.hasOwnProperty('landLineAvailability')) {
        obj['landLineAvailability'] = AvailabilityEnum.constructFromObject(data['landLineAvailability']);
      }
    }
    return obj;
  }

  /**
   * Contains the default values for a new mobile phone
   * @member {module:model/PhoneNew} mobilePhone
   */
  exports.prototype['mobilePhone'] = undefined;
  /**
   * Contains the default values for a new land-line phone
   * @member {module:model/PhoneNew} landLinePhone
   */
  exports.prototype['landLinePhone'] = undefined;
  /**
   * The availability for mobile phones Possible values are: * disabled: The data is disabled * optional: The data is enabled and optional * required: The data is enabled and required 
   * @member {module:model/AvailabilityEnum} mobileAvailability
   */
  exports.prototype['mobileAvailability'] = undefined;
  /**
   * The availability for mobile phones Possible values are: * disabled: The data is disabled * optional: The data is enabled and optional * required: The data is enabled and required 
   * @member {module:model/AvailabilityEnum} landLineAvailability
   */
  exports.prototype['landLineAvailability'] = undefined;

  // Implement PhoneConfiguration interface:
  /**
   * The 2-letter country code used by default for numbers. Unless an international number is specified (using the `+` prefix), the phone number is assumed to belong to this country. 
   * @member {String} country
   */
exports.prototype['country'] = undefined;

  /**
   * Indicates the it is configured to always format numbers using the international format. If set to false, numbers will be formatted in the national format. 
   * @member {Boolean} alwaysShowInternationalNumber
   */
exports.prototype['alwaysShowInternationalNumber'] = undefined;

  /**
   * Indicates whether the extension is enabled for land-line phones
   * @member {Boolean} extensionEnabled
   */
exports.prototype['extensionEnabled'] = undefined;

  /**
   * Indicates whether outbound SMS is enabled in Cyclos
   * @member {Boolean} smsEnabled
   */
exports.prototype['smsEnabled'] = undefined;

  /**
   * An example phone number for a land-line phone
   * @member {String} landLineExample
   */
exports.prototype['landLineExample'] = undefined;

  /**
   * An example phone number for a mobile phone
   * @member {String} mobileExample
   */
exports.prototype['mobileExample'] = undefined;



  return exports;
}));


