/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.PreselectedPeriod = factory(root.Cyclos471Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PreselectedPeriod model module.
   * @module model/PreselectedPeriod
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>PreselectedPeriod</code>.
   * Represents a pre-calculated date period 
   * @alias module:model/PreselectedPeriod
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>PreselectedPeriod</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PreselectedPeriod} obj Optional instance to populate.
   * @return {module:model/PreselectedPeriod} The populated <code>PreselectedPeriod</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('defaultOption')) {
        obj['defaultOption'] = ApiClient.convertToType(data['defaultOption'], 'Boolean');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('begin')) {
        obj['begin'] = ApiClient.convertToType(data['begin'], 'Date');
      }
      if (data.hasOwnProperty('end')) {
        obj['end'] = ApiClient.convertToType(data['end'], 'Date');
      }
    }
    return obj;
  }

  /**
   * Indicates whether this period should be pre-selected
   * @member {Boolean} defaultOption
   */
  exports.prototype['defaultOption'] = undefined;
  /**
   * The period display name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The period begin date
   * @member {Date} begin
   */
  exports.prototype['begin'] = undefined;
  /**
   * The period begin date
   * @member {Date} end
   */
  exports.prototype['end'] = undefined;



  return exports;
}));


