/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InternalNamedEntity', 'model/PrincipalTypeKind'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InternalNamedEntity'), require('./PrincipalTypeKind'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.PrincipalType = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.InternalNamedEntity, root.Cyclos471Api.PrincipalTypeKind);
  }
}(this, function(ApiClient, InternalNamedEntity, PrincipalTypeKind) {
  'use strict';




  /**
   * The PrincipalType model module.
   * @module model/PrincipalType
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>PrincipalType</code>.
   * A reference to a principal type
   * @alias module:model/PrincipalType
   * @class
   * @implements module:model/InternalNamedEntity
   */
  var exports = function() {
    var _this = this;

    InternalNamedEntity.call(_this);

  };

  /**
   * Constructs a <code>PrincipalType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrincipalType} obj Optional instance to populate.
   * @return {module:model/PrincipalType} The populated <code>PrincipalType</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      InternalNamedEntity.constructFromObject(data, obj);
      if (data.hasOwnProperty('kind')) {
        obj['kind'] = PrincipalTypeKind.constructFromObject(data['kind']);
      }
    }
    return obj;
  }

  /**
   * The kind of this principal type
   * @member {module:model/PrincipalTypeKind} kind
   */
  exports.prototype['kind'] = undefined;

  // Implement InternalNamedEntity interface:
  /**
   * Entity identifier
   * @member {String} id
   */
exports.prototype['id'] = undefined;

  /**
   * The entity name
   * @member {String} name
   */
exports.prototype['name'] = undefined;

  /**
   * The entity internal name, which can be seen as an extra identifier 
   * @member {String} internalName
   */
exports.prototype['internalName'] = undefined;



  return exports;
}));


