/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RecordKind', 'model/RecordResult', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RecordKind'), require('./RecordResult'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.RecordWithOwnerResult = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.RecordKind, root.Cyclos471Api.RecordResult, root.Cyclos471Api.User);
  }
}(this, function(ApiClient, RecordKind, RecordResult, User) {
  'use strict';




  /**
   * The RecordWithOwnerResult model module.
   * @module model/RecordWithOwnerResult
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>RecordWithOwnerResult</code>.
   * Results for a shared record search, containing the owner user as well 
   * @alias module:model/RecordWithOwnerResult
   * @class
   * @implements module:model/RecordResult
   */
  var exports = function() {
    var _this = this;

    RecordResult.call(_this);

  };

  /**
   * Constructs a <code>RecordWithOwnerResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecordWithOwnerResult} obj Optional instance to populate.
   * @return {module:model/RecordWithOwnerResult} The populated <code>RecordWithOwnerResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      RecordResult.constructFromObject(data, obj);
      if (data.hasOwnProperty('user')) {
        obj['user'] = User.constructFromObject(data['user']);
      }
    }
    return obj;
  }

  /**
   * The record owner
   * @member {module:model/User} user
   */
  exports.prototype['user'] = undefined;

  // Implement RecordResult interface:
  /**
   * Entity identifier
   * @member {String} id
   */
exports.prototype['id'] = undefined;

  /**
   * The possible kinds of a record, which can either belong to system or to an user Possible values are: * user: The record belongs to a specific user * system: The record belongs to the system, and is unrelated to an user 
   * @member {module:model/RecordKind} kind
   */
exports.prototype['kind'] = undefined;

  /**
   * The record creation date
   * @member {Date} creationDate
   */
exports.prototype['creationDate'] = undefined;

  /**
   * Reference to the user that created the record
   * @member {module:model/User} createdBy
   */
exports.prototype['createdBy'] = undefined;

  /**
   * The record last modification date
   * @member {Date} lastModificationDate
   */
exports.prototype['lastModificationDate'] = undefined;

  /**
   * Reference to the user that last modified the record
   * @member {module:model/User} lastModifiedBy
   */
exports.prototype['lastModifiedBy'] = undefined;

  /**
   * Holds the values for custom record fields, keyed by field internal name 
   * @member {Object.<String, String>} customValues
   */
exports.prototype['customValues'] = undefined;



  return exports;
}));


