/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BigDecimal', 'model/Entity', 'model/RecurringPaymentOccurrenceStatusEnum', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BigDecimal'), require('./Entity'), require('./RecurringPaymentOccurrenceStatusEnum'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.RecurringPaymentOccurrence = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.BigDecimal, root.Cyclos471Api.Entity, root.Cyclos471Api.RecurringPaymentOccurrenceStatusEnum, root.Cyclos471Api.User);
  }
}(this, function(ApiClient, BigDecimal, Entity, RecurringPaymentOccurrenceStatusEnum, User) {
  'use strict';




  /**
   * The RecurringPaymentOccurrence model module.
   * @module model/RecurringPaymentOccurrence
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>RecurringPaymentOccurrence</code>.
   * Contains details about an occurrence of a recurring payment 
   * @alias module:model/RecurringPaymentOccurrence
   * @class
   * @implements module:model/Entity
   */
  var exports = function() {
    var _this = this;

    Entity.call(_this);







  };

  /**
   * Constructs a <code>RecurringPaymentOccurrence</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecurringPaymentOccurrence} obj Optional instance to populate.
   * @return {module:model/RecurringPaymentOccurrence} The populated <code>RecurringPaymentOccurrence</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('number')) {
        obj['number'] = ApiClient.convertToType(data['number'], 'Number');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], BigDecimal);
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = RecurringPaymentOccurrenceStatusEnum.constructFromObject(data['status']);
      }
      if (data.hasOwnProperty('by')) {
        obj['by'] = User.constructFromObject(data['by']);
      }
      if (data.hasOwnProperty('transferId')) {
        obj['transferId'] = ApiClient.convertToType(data['transferId'], 'String');
      }
      if (data.hasOwnProperty('transferDate')) {
        obj['transferDate'] = ApiClient.convertToType(data['transferDate'], 'Date');
      }
    }
    return obj;
  }

  /**
   * The occurrence number.
   * @member {Number} number
   */
  exports.prototype['number'] = undefined;
  /**
   * The occurrence date.
   * @member {Date} date
   */
  exports.prototype['date'] = undefined;
  /**
   * The installment amount
   * @member {module:model/BigDecimal} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * The status of a recurring payment occurrence Possible values are: * processed: The occurrence was correctly processed, generating a transfer * failed: The occurrence has failed processing (probably because there was not enough funds in the payer account) 
   * @member {module:model/RecurringPaymentOccurrenceStatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * The user that performed an status change. For example, who manually paid, settled or canceled an open installment 
   * @member {module:model/User} by
   */
  exports.prototype['by'] = undefined;
  /**
   * Only if the installment was processed, contains the internal identifier of the generated transfer. 
   * @member {String} transferId
   */
  exports.prototype['transferId'] = undefined;
  /**
   * The date the transfer was processed. It might happen that the occurrence has first failed, then later processed 
   * @member {Date} transferDate
   */
  exports.prototype['transferDate'] = undefined;

  // Implement Entity interface:
  /**
   * Entity identifier
   * @member {String} id
   */
exports.prototype['id'] = undefined;



  return exports;
}));


