/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.RedeemVoucher = factory(root.Cyclos471Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RedeemVoucher model module.
   * @module model/RedeemVoucher
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>RedeemVoucher</code>.
   * Additional data to redeem a voucher
   * @alias module:model/RedeemVoucher
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>RedeemVoucher</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RedeemVoucher} obj Optional instance to populate.
   * @return {module:model/RedeemVoucher} The populated <code>RedeemVoucher</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('customValues')) {
        obj['customValues'] = ApiClient.convertToType(data['customValues'], {'String': 'String'});
      }
    }
    return obj;
  }

  /**
   * Holds the custom field values for the redeem payment, keyed by field internal name or id. The format of the value depends on the custom field type. 
   * @member {Object.<String, String>} customValues
   */
  exports.prototype['customValues'] = undefined;



  return exports;
}));


