/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BigDecimal', 'model/EntityReference'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BigDecimal'), require('./EntityReference'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.TransferFeePreview = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.BigDecimal, root.Cyclos471Api.EntityReference);
  }
}(this, function(ApiClient, BigDecimal, EntityReference) {
  'use strict';




  /**
   * The TransferFeePreview model module.
   * @module model/TransferFeePreview
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>TransferFeePreview</code>.
   * Preview of a transfer fee in case a payment is confirmed
   * @alias module:model/TransferFeePreview
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TransferFeePreview</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransferFeePreview} obj Optional instance to populate.
   * @return {module:model/TransferFeePreview} The populated <code>TransferFeePreview</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fee')) {
        obj['fee'] = EntityReference.constructFromObject(data['fee']);
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], BigDecimal);
      }
    }
    return obj;
  }

  /**
   * The transfer fee
   * @member {module:model/EntityReference} fee
   */
  exports.prototype['fee'] = undefined;
  /**
   * The transfer fee amout
   * @member {module:model/BigDecimal} amount
   */
  exports.prototype['amount'] = undefined;



  return exports;
}));


