/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BaseTransferDataForSearch', 'model/Currency', 'model/EntityReference', 'model/Group', 'model/PreselectedPeriod', 'model/TransferFilter', 'model/TransferKind', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BaseTransferDataForSearch'), require('./Currency'), require('./EntityReference'), require('./Group'), require('./PreselectedPeriod'), require('./TransferFilter'), require('./TransferKind'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.TransferDataForSearch = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.BaseTransferDataForSearch, root.Cyclos471Api.Currency, root.Cyclos471Api.EntityReference, root.Cyclos471Api.Group, root.Cyclos471Api.PreselectedPeriod, root.Cyclos471Api.TransferFilter, root.Cyclos471Api.TransferKind, root.Cyclos471Api.User);
  }
}(this, function(ApiClient, BaseTransferDataForSearch, Currency, EntityReference, Group, PreselectedPeriod, TransferFilter, TransferKind, User) {
  'use strict';




  /**
   * The TransferDataForSearch model module.
   * @module model/TransferDataForSearch
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>TransferDataForSearch</code>.
   * Contains data for searching transfers over multiple accounts
   * @alias module:model/TransferDataForSearch
   * @class
   * @implements module:model/BaseTransferDataForSearch
   */
  var exports = function() {
    var _this = this;

    BaseTransferDataForSearch.call(_this);




  };

  /**
   * Constructs a <code>TransferDataForSearch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransferDataForSearch} obj Optional instance to populate.
   * @return {module:model/TransferDataForSearch} The populated <code>TransferDataForSearch</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      BaseTransferDataForSearch.constructFromObject(data, obj);
      if (data.hasOwnProperty('accountTypes')) {
        obj['accountTypes'] = ApiClient.convertToType(data['accountTypes'], [EntityReference]);
      }
      if (data.hasOwnProperty('currencies')) {
        obj['currencies'] = ApiClient.convertToType(data['currencies'], [Currency]);
      }
      if (data.hasOwnProperty('defaultKinds')) {
        obj['defaultKinds'] = ApiClient.convertToType(data['defaultKinds'], [TransferKind]);
      }
      if (data.hasOwnProperty('defaultHideChargedBack')) {
        obj['defaultHideChargedBack'] = ApiClient.convertToType(data['defaultHideChargedBack'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * References for the account types 
   * @member {Array.<module:model/EntityReference>} accountTypes
   */
  exports.prototype['accountTypes'] = undefined;
  /**
   * References for the available currencies 
   * @member {Array.<module:model/Currency>} currencies
   */
  exports.prototype['currencies'] = undefined;
  /**
   * The transfer kinds that should be searched by default Possibles values for each array element are: * payment: A transfer generated by a direct payment or accepting a webshop order * scheduledPaymentInstallment: A transfer generated when processing a scheduled payment installment * recurringPayment: A transfer generated when processing a recurring payment * chargeback: A transfer which is a chargeback of another transfer * initialCredit: A transfer which is the initial credit for a newly created account * transferFee: A transfer generated by a transfer fee charge * accountFee: A transfer generated by an account fee charge * import: An imported transfer 
   * @member {Array.<module:model/TransferKind>} defaultKinds
   */
  exports.prototype['defaultKinds'] = undefined;
  /**
   * Indicats whether clients should set the query to hide transfers that were charged-back by default, by setting the `chargedBack` parameter to `false` on search. 
   * @member {Boolean} defaultHideChargedBack
   */
  exports.prototype['defaultHideChargedBack'] = undefined;

  // Implement BaseTransferDataForSearch interface:
  /**
   * References for transfer filters, which can be used to filter entries by transfer type 
   * @member {Array.<module:model/TransferFilter>} transferFilters
   */
exports.prototype['transferFilters'] = undefined;

  /**
   * References for channels which can be used to filter entries by transfers generated on a specific channel. Is only returned if the authenticated user is an administrator. 
   * @member {Array.<module:model/EntityReference>} channels
   */
exports.prototype['channels'] = undefined;

  /**
   * Groups that can be used to filter entries, so that only transfers from or to users of those groups are returned on search. Is only returned if the authenticated user is an administrator. 
   * @member {Array.<module:model/Group>} groups
   */
exports.prototype['groups'] = undefined;

  /**
   * References for access clients which can be used to filter entries by transfers generated by a specific access client  
   * @member {Array.<module:model/EntityReference>} accessClients
   */
exports.prototype['accessClients'] = undefined;

  /**
   * References for operators, which can be used to filter entries by transfers performed or received by that specific operator  
   * @member {Array.<module:model/User>} operators
   */
exports.prototype['operators'] = undefined;

  /**
   * Contains the pre-selected period filter ranges according to the Cyclos configuration   
   * @member {Array.<module:model/PreselectedPeriod>} preselectedPeriods
   */
exports.prototype['preselectedPeriods'] = undefined;



  return exports;
}));


