/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AmountSummary'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AmountSummary'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.UserBalancesSummary = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.AmountSummary);
  }
}(this, function(ApiClient, AmountSummary) {
  'use strict';




  /**
   * The UserBalancesSummary model module.
   * @module model/UserBalancesSummary
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>UserBalancesSummary</code>.
   * Contains summarized information about balances per range, plus the total 
   * @alias module:model/UserBalancesSummary
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>UserBalancesSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserBalancesSummary} obj Optional instance to populate.
   * @return {module:model/UserBalancesSummary} The populated <code>UserBalancesSummary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('low')) {
        obj['low'] = AmountSummary.constructFromObject(data['low']);
      }
      if (data.hasOwnProperty('medium')) {
        obj['medium'] = AmountSummary.constructFromObject(data['medium']);
      }
      if (data.hasOwnProperty('high')) {
        obj['high'] = AmountSummary.constructFromObject(data['high']);
      }
      if (data.hasOwnProperty('total')) {
        obj['total'] = AmountSummary.constructFromObject(data['total']);
      }
    }
    return obj;
  }

  /**
   * Summary of low balances. Is only returned when a medium balance range is defined, either in the account type or in the query parameters.  
   * @member {module:model/AmountSummary} low
   */
  exports.prototype['low'] = undefined;
  /**
   * Summary of medium balances. Is only returned when a medium balance range is defined, either in the account type or in the query parameters.  
   * @member {module:model/AmountSummary} medium
   */
  exports.prototype['medium'] = undefined;
  /**
   * Summary of high balances. Is only returned when a medium balance range is defined, either in the account type or in the query parameters.  
   * @member {module:model/AmountSummary} high
   */
  exports.prototype['high'] = undefined;
  /**
   * Summary of all balances.  
   * @member {module:model/AmountSummary} total
   */
  exports.prototype['total'] = undefined;



  return exports;
}));


