/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntityReference'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntityReference'));
  } else {
    // Browser globals (root is window)
    if (!root.Cyclos471Api) {
      root.Cyclos471Api = {};
    }
    root.Cyclos471Api.UserVouchersDataForSearch = factory(root.Cyclos471Api.ApiClient, root.Cyclos471Api.EntityReference);
  }
}(this, function(ApiClient, EntityReference) {
  'use strict';




  /**
   * The UserVouchersDataForSearch model module.
   * @module model/UserVouchersDataForSearch
   * @version 4.7.1
   */

  /**
   * Constructs a new <code>UserVouchersDataForSearch</code>.
   * Contains configuration data for searching vouchers of an user 
   * @alias module:model/UserVouchersDataForSearch
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>UserVouchersDataForSearch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserVouchersDataForSearch} obj Optional instance to populate.
   * @return {module:model/UserVouchersDataForSearch} The populated <code>UserVouchersDataForSearch</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mask')) {
        obj['mask'] = ApiClient.convertToType(data['mask'], 'String');
      }
      if (data.hasOwnProperty('types')) {
        obj['types'] = ApiClient.convertToType(data['types'], [EntityReference]);
      }
    }
    return obj;
  }

  /**
   * The input mask for voucher tokens. Optional.
   * @member {String} mask
   */
  exports.prototype['mask'] = undefined;
  /**
   * The voucher types that can be used for searching
   * @member {Array.<module:model/EntityReference>} types
   */
  exports.prototype['types'] = undefined;



  return exports;
}));


