/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cyclos471Api);
  }
}(this, function(expect, Cyclos471Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cyclos471Api.AccountStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountStatus', function() {
    it('should create an instance of AccountStatus', function() {
      // uncomment below and update the code to test AccountStatus
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be.a(Cyclos471Api.AccountStatus);
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be();
    });

    it('should have the property creditLimit (base name: "creditLimit")', function() {
      // uncomment below and update the code to test the property creditLimit
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be();
    });

    it('should have the property upperCreditLimit (base name: "upperCreditLimit")', function() {
      // uncomment below and update the code to test the property upperCreditLimit
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be();
    });

    it('should have the property reservedAmount (base name: "reservedAmount")', function() {
      // uncomment below and update the code to test the property reservedAmount
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be();
    });

    it('should have the property availableBalance (base name: "availableBalance")', function() {
      // uncomment below and update the code to test the property availableBalance
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be();
    });

    it('should have the property negativeSince (base name: "negativeSince")', function() {
      // uncomment below and update the code to test the property negativeSince
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be();
    });

    it('should have the property aRate (base name: "ARate")', function() {
      // uncomment below and update the code to test the property aRate
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be();
    });

    it('should have the property dRate (base name: "DRate")', function() {
      // uncomment below and update the code to test the property dRate
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be();
    });

    it('should have the property rateBalanceCorrection (base name: "rateBalanceCorrection")', function() {
      // uncomment below and update the code to test the property rateBalanceCorrection
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be();
    });

    it('should have the property virtualRatedBalance (base name: "virtualRatedBalance")', function() {
      // uncomment below and update the code to test the property virtualRatedBalance
      //var instane = new Cyclos471Api.AccountStatus();
      //expect(instance).to.be();
    });

  });

}));
