/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cyclos471Api);
  }
}(this, function(expect, Cyclos471Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cyclos471Api.DataForTransaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DataForTransaction', function() {
    it('should create an instance of DataForTransaction', function() {
      // uncomment below and update the code to test DataForTransaction
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be.a(Cyclos471Api.DataForTransaction);
    });

    it('should have the property accounts (base name: "accounts")', function() {
      // uncomment below and update the code to test the property accounts
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property fromKind (base name: "fromKind")', function() {
      // uncomment below and update the code to test the property fromKind
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property fromUser (base name: "fromUser")', function() {
      // uncomment below and update the code to test the property fromUser
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property toKind (base name: "toKind")', function() {
      // uncomment below and update the code to test the property toKind
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property toUser (base name: "toUser")', function() {
      // uncomment below and update the code to test the property toUser
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property paymentTypeData (base name: "paymentTypeData")', function() {
      // uncomment below and update the code to test the property paymentTypeData
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property paymentTypes (base name: "paymentTypes")', function() {
      // uncomment below and update the code to test the property paymentTypes
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property allowAutocomplete (base name: "allowAutocomplete")', function() {
      // uncomment below and update the code to test the property allowAutocomplete
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property allowContacts (base name: "allowContacts")', function() {
      // uncomment below and update the code to test the property allowContacts
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property principalTypes (base name: "principalTypes")', function() {
      // uncomment below and update the code to test the property principalTypes
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property defaultIdMethod (base name: "defaultIdMethod")', function() {
      // uncomment below and update the code to test the property defaultIdMethod
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

    it('should have the property defaultPrincipalType (base name: "defaultPrincipalType")', function() {
      // uncomment below and update the code to test the property defaultPrincipalType
      //var instane = new Cyclos471Api.DataForTransaction();
      //expect(instance).to.be();
    });

  });

}));
