/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cyclos471Api);
  }
}(this, function(expect, Cyclos471Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cyclos471Api.PerformTransaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PerformTransaction', function() {
    it('should create an instance of PerformTransaction', function() {
      // uncomment below and update the code to test PerformTransaction
      //var instane = new Cyclos471Api.PerformTransaction();
      //expect(instance).to.be.a(Cyclos471Api.PerformTransaction);
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instane = new Cyclos471Api.PerformTransaction();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new Cyclos471Api.PerformTransaction();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Cyclos471Api.PerformTransaction();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new Cyclos471Api.PerformTransaction();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new Cyclos471Api.PerformTransaction();
      //expect(instance).to.be();
    });

    it('should have the property customValues (base name: "customValues")', function() {
      // uncomment below and update the code to test the property customValues
      //var instane = new Cyclos471Api.PerformTransaction();
      //expect(instance).to.be();
    });

    it('should have the property nfcChallence (base name: "nfcChallence")', function() {
      // uncomment below and update the code to test the property nfcChallence
      //var instane = new Cyclos471Api.PerformTransaction();
      //expect(instance).to.be();
    });

  });

}));
