/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cyclos471Api);
  }
}(this, function(expect, Cyclos471Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cyclos471Api.Transaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Transaction', function() {
    it('should create an instance of Transaction', function() {
      // uncomment below and update the code to test Transaction
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be.a(Cyclos471Api.Transaction);
    });

    it('should have the property transactionNumber (base name: "transactionNumber")', function() {
      // uncomment below and update the code to test the property transactionNumber
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property kind (base name: "kind")', function() {
      // uncomment below and update the code to test the property kind
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property fromKind (base name: "fromKind")', function() {
      // uncomment below and update the code to test the property fromKind
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property fromUser (base name: "fromUser")', function() {
      // uncomment below and update the code to test the property fromUser
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property toKind (base name: "toKind")', function() {
      // uncomment below and update the code to test the property toKind
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property toUser (base name: "toUser")', function() {
      // uncomment below and update the code to test the property toUser
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property authorizationStatus (base name: "authorizationStatus")', function() {
      // uncomment below and update the code to test the property authorizationStatus
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Cyclos471Api.Transaction();
      //expect(instance).to.be();
    });

  });

}));
