/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cyclos471Api);
  }
}(this, function(expect, Cyclos471Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cyclos471Api.UserPermissions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserPermissions', function() {
    it('should create an instance of UserPermissions', function() {
      // uncomment below and update the code to test UserPermissions
      //var instane = new Cyclos471Api.UserPermissions();
      //expect(instance).to.be.a(Cyclos471Api.UserPermissions);
    });

    it('should have the property profile (base name: "profile")', function() {
      // uncomment below and update the code to test the property profile
      //var instane = new Cyclos471Api.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property contact (base name: "contact")', function() {
      // uncomment below and update the code to test the property contact
      //var instane = new Cyclos471Api.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property marketplace (base name: "marketplace")', function() {
      // uncomment below and update the code to test the property marketplace
      //var instane = new Cyclos471Api.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property accounts (base name: "accounts")', function() {
      // uncomment below and update the code to test the property accounts
      //var instane = new Cyclos471Api.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property payment (base name: "payment")', function() {
      // uncomment below and update the code to test the property payment
      //var instane = new Cyclos471Api.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property records (base name: "records")', function() {
      // uncomment below and update the code to test the property records
      //var instane = new Cyclos471Api.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property tokens (base name: "tokens")', function() {
      // uncomment below and update the code to test the property tokens
      //var instane = new Cyclos471Api.UserPermissions();
      //expect(instance).to.be();
    });

    it('should have the property personalizeNfcTokens (base name: "personalizeNfcTokens")', function() {
      // uncomment below and update the code to test the property personalizeNfcTokens
      //var instane = new Cyclos471Api.UserPermissions();
      //expect(instance).to.be();
    });

  });

}));
