/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cyclos471Api);
  }
}(this, function(expect, Cyclos471Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cyclos471Api.UserNew();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserNew', function() {
    it('should create an instance of UserNew', function() {
      // uncomment below and update the code to test UserNew
      //var instane = new Cyclos471Api.UserNew();
      //expect(instance).to.be.a(Cyclos471Api.UserNew);
    });

    it('should have the property group (base name: "group")', function() {
      // uncomment below and update the code to test the property group
      //var instane = new Cyclos471Api.UserNew();
      //expect(instance).to.be();
    });

    it('should have the property addresses (base name: "addresses")', function() {
      // uncomment below and update the code to test the property addresses
      //var instane = new Cyclos471Api.UserNew();
      //expect(instance).to.be();
    });

    it('should have the property mobilePhones (base name: "mobilePhones")', function() {
      // uncomment below and update the code to test the property mobilePhones
      //var instane = new Cyclos471Api.UserNew();
      //expect(instance).to.be();
    });

    it('should have the property landLinePhones (base name: "landLinePhones")', function() {
      // uncomment below and update the code to test the property landLinePhones
      //var instane = new Cyclos471Api.UserNew();
      //expect(instance).to.be();
    });

    it('should have the property passwords (base name: "passwords")', function() {
      // uncomment below and update the code to test the property passwords
      //var instane = new Cyclos471Api.UserNew();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instane = new Cyclos471Api.UserNew();
      //expect(instance).to.be();
    });

    it('should have the property captcha (base name: "captcha")', function() {
      // uncomment below and update the code to test the property captcha
      //var instane = new Cyclos471Api.UserNew();
      //expect(instance).to.be();
    });

    it('should have the property acceptAgreement (base name: "acceptAgreement")', function() {
      // uncomment below and update the code to test the property acceptAgreement
      //var instane = new Cyclos471Api.UserNew();
      //expect(instance).to.be();
    });

    it('should have the property skipActivationEmail (base name: "skipActivationEmail")', function() {
      // uncomment below and update the code to test the property skipActivationEmail
      //var instane = new Cyclos471Api.UserNew();
      //expect(instance).to.be();
    });

  });

}));
