/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cyclos471Api);
  }
}(this, function(expect, Cyclos471Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cyclos471Api.UserView();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserView', function() {
    it('should create an instance of UserView', function() {
      // uncomment below and update the code to test UserView
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be.a(Cyclos471Api.UserView);
    });

    it('should have the property role (base name: "role")', function() {
      // uncomment below and update the code to test the property role
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property customValues (base name: "customValues")', function() {
      // uncomment below and update the code to test the property customValues
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property group (base name: "group")', function() {
      // uncomment below and update the code to test the property group
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property groupSet (base name: "groupSet")', function() {
      // uncomment below and update the code to test the property groupSet
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property additionalImages (base name: "additionalImages")', function() {
      // uncomment below and update the code to test the property additionalImages
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property addresses (base name: "addresses")', function() {
      // uncomment below and update the code to test the property addresses
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property phones (base name: "phones")', function() {
      // uncomment below and update the code to test the property phones
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property contact (base name: "contact")', function() {
      // uncomment below and update the code to test the property contact
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

    it('should have the property permissions (base name: "permissions")', function() {
      // uncomment below and update the code to test the property permissions
      //var instane = new Cyclos471Api.UserView();
      //expect(instance).to.be();
    });

  });

}));
