/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cyclos471Api);
  }
}(this, function(expect, Cyclos471Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cyclos471Api.AccountsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountsApi', function() {
    describe('getAccountHistoryDataByOwnerAndType', function() {
      it('should call getAccountHistoryDataByOwnerAndType successfully', function(done) {
        //uncomment below and update the code to test getAccountHistoryDataByOwnerAndType
        //instance.getAccountHistoryDataByOwnerAndType(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAccountStatusByOwnerAndType', function() {
      it('should call getAccountStatusByOwnerAndType successfully', function(done) {
        //uncomment below and update the code to test getAccountStatusByOwnerAndType
        //instance.getAccountStatusByOwnerAndType(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBalancesData', function() {
      it('should call getUserBalancesData successfully', function(done) {
        //uncomment below and update the code to test getUserBalancesData
        //instance.getUserBalancesData(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBalancesSummary', function() {
      it('should call getUserBalancesSummary successfully', function(done) {
        //uncomment below and update the code to test getUserBalancesSummary
        //instance.getUserBalancesSummary(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAccountsByOwner', function() {
      it('should call listAccountsByOwner successfully', function(done) {
        //uncomment below and update the code to test listAccountsByOwner
        //instance.listAccountsByOwner(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchAccountHistory', function() {
      it('should call searchAccountHistory successfully', function(done) {
        //uncomment below and update the code to test searchAccountHistory
        //instance.searchAccountHistory(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchUsersWithBalances', function() {
      it('should call searchUsersWithBalances successfully', function(done) {
        //uncomment below and update the code to test searchUsersWithBalances
        //instance.searchUsersWithBalances(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
