/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cyclos471Api);
  }
}(this, function(expect, Cyclos471Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cyclos471Api.OperatorsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OperatorsApi', function() {
    describe('getGeneralOperatorsDataForSearch', function() {
      it('should call getGeneralOperatorsDataForSearch successfully', function(done) {
        //uncomment below and update the code to test getGeneralOperatorsDataForSearch
        //instance.getGeneralOperatorsDataForSearch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserOperatorsDataForSearch', function() {
      it('should call getUserOperatorsDataForSearch successfully', function(done) {
        //uncomment below and update the code to test getUserOperatorsDataForSearch
        //instance.getUserOperatorsDataForSearch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchGeneralOperators', function() {
      it('should call searchGeneralOperators successfully', function(done) {
        //uncomment below and update the code to test searchGeneralOperators
        //instance.searchGeneralOperators(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchUserOperators', function() {
      it('should call searchUserOperators successfully', function(done) {
        //uncomment below and update the code to test searchUserOperators
        //instance.searchUserOperators(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
