/**
 * Cyclos 4.7.1 API
 * The REST API for Cyclos 4.7.1
 *
 * OpenAPI spec version: 4.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cyclos471Api);
  }
}(this, function(expect, Cyclos471Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cyclos471Api.PhonesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PhonesApi', function() {
    describe('createPhone', function() {
      it('should call createPhone successfully', function(done) {
        //uncomment below and update the code to test createPhone
        //instance.createPhone(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePhone', function() {
      it('should call deletePhone successfully', function(done) {
        //uncomment below and update the code to test deletePhone
        //instance.deletePhone(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('disablePhoneForSms', function() {
      it('should call disablePhoneForSms successfully', function(done) {
        //uncomment below and update the code to test disablePhoneForSms
        //instance.disablePhoneForSms(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enablePhoneForSms', function() {
      it('should call enablePhoneForSms successfully', function(done) {
        //uncomment below and update the code to test enablePhoneForSms
        //instance.enablePhoneForSms(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhoneDataForEdit', function() {
      it('should call getPhoneDataForEdit successfully', function(done) {
        //uncomment below and update the code to test getPhoneDataForEdit
        //instance.getPhoneDataForEdit(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhoneDataForNew', function() {
      it('should call getPhoneDataForNew successfully', function(done) {
        //uncomment below and update the code to test getPhoneDataForNew
        //instance.getPhoneDataForNew(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserPhonesListData', function() {
      it('should call getUserPhonesListData successfully', function(done) {
        //uncomment below and update the code to test getUserPhonesListData
        //instance.getUserPhonesListData(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listPhonesByUser', function() {
      it('should call listPhonesByUser successfully', function(done) {
        //uncomment below and update the code to test listPhonesByUser
        //instance.listPhonesByUser(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendPhoneVerificationCode', function() {
      it('should call sendPhoneVerificationCode successfully', function(done) {
        //uncomment below and update the code to test sendPhoneVerificationCode
        //instance.sendPhoneVerificationCode(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePhone', function() {
      it('should call updatePhone successfully', function(done) {
        //uncomment below and update the code to test updatePhone
        //instance.updatePhone(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('verifyPhone', function() {
      it('should call verifyPhone successfully', function(done) {
        //uncomment below and update the code to test verifyPhone
        //instance.verifyPhone(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('viewPhone', function() {
      it('should call viewPhone successfully', function(done) {
        //uncomment below and update the code to test viewPhone
        //instance.viewPhone(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
